<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Plan de pruebas" duration-ms="0" started-at="2018-03-12T04:55:06Z" finished-at="2018-03-12T04:55:06Z">
    <groups>
    </groups>
  </suite> <!-- Plan de pruebas -->
  <suite name="Pruebas de Aritmetica" duration-ms="335" started-at="2018-03-12T04:55:05Z" finished-at="2018-03-12T04:55:06Z">
    <groups>
    </groups>
    <test name="Prueba de operaciones basicas" duration-ms="335" started-at="2018-03-12T04:55:05Z" finished-at="2018-03-12T04:55:06Z">
      <class name="PracticaEclipse.Unitarias.AritmeticaTest">
        <test-method status="PASS" signature="setUp(int, int)[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="setUp" is-config="true" duration-ms="53" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDivision()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="testDivision" duration-ms="34" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivision -->
        <test-method status="PASS" signature="testMultiplicacion()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="testMultiplicacion" duration-ms="6" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMultiplicacion -->
        <test-method status="FAIL" signature="testMultiplicacion2()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="testMultiplicacion2" duration-ms="144" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No da el mismo resultado se esperaba: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No da el mismo resultado se esperaba: 4
	at org.testng.Assert.fail(Assert.java:94)
	at PracticaEclipse.Unitarias.AritmeticaTest.testMultiplicacion2(AritmeticaTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1194)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMultiplicacion2 -->
        <test-method status="FAIL" signature="testResta()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="testResta" duration-ms="7" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No da el mismo resultado se espereba: 5]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No da el mismo resultado se espereba: 5
	at org.testng.Assert.fail(Assert.java:94)
	at PracticaEclipse.Unitarias.AritmeticaTest.testResta(AritmeticaTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1194)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResta -->
        <test-method status="PASS" signature="testSuma()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="testSuma" duration-ms="4" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuma -->
        <test-method status="PASS" signature="setOut()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@20e3c449]" name="setOut" is-config="true" duration-ms="0" started-at="2018-03-11T22:55:06Z" finished-at="2018-03-11T22:55:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setOut -->
      </class> <!-- PracticaEclipse.Unitarias.AritmeticaTest -->
    </test> <!-- Prueba de operaciones basicas -->
  </suite> <!-- Pruebas de Aritmetica -->
</testng-results>
