<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OCTI107.local" name="PracticaEclipse.Unitarias.AritmeticaTest" tests="5" failures="1" timestamp="12 Mar 2018 05:19:58 GMT" time="0.180" errors="0">
  <testcase name="testMultiplicacion" time="0.005" classname="PracticaEclipse.Unitarias.AritmeticaTest"/>
  <testcase name="testDivision" time="0.030" classname="PracticaEclipse.Unitarias.AritmeticaTest"/>
  <testcase name="testSuma" time="0.006" classname="PracticaEclipse.Unitarias.AritmeticaTest"/>
  <testcase name="testResta" time="0.006" classname="PracticaEclipse.Unitarias.AritmeticaTest"/>
  <testcase name="testMultiplicacion2" time="0.133" classname="PracticaEclipse.Unitarias.AritmeticaTest">
    <failure type="java.lang.AssertionError" message="No da el mismo resultado se esperaba: 4">
      <![CDATA[java.lang.AssertionError: No da el mismo resultado se esperaba: 4
	at org.testng.Assert.fail(Assert.java:94)
	at PracticaEclipse.Unitarias.AritmeticaTest.testMultiplicacion2(AritmeticaTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMultiplicacion2 -->
</testsuite> <!-- PracticaEclipse.Unitarias.AritmeticaTest -->
